// Sample decisions, the default company, and two sample committee runs so the
// deployed site shows a full committee even without an API key. The runs are
// written for the demo and labelled "sample run" wherever they appear.

export const DEFAULT_CONTEXT = 'Mid-size industrial group headquartered in Dammam, Saudi Arabia: steel fabrication and building products, about SAR 2.5 bn revenue and 1,800 staff, listed on Tadawul, 60% Saudi-owned. Corporate WACC 8.5%, hurdle rate 12%. Board has a public net-zero 2060 pledge aligned with the Saudi Green Initiative. High Green Nitaqat band. Key customers include Aramco-tier suppliers and giga-project contractors.';

export const SAMPLES = [
  {
    id: 'solar',
    title: '10 MWp solar at our Jubail plant',
    decision: 'Approve $6.0M capex for a 10 MWp ground-mount and rooftop solar PV system at our Jubail fabrication plant, offsetting grid purchases at the SAR 0.20/kWh industrial tariff. 25-year asset life; EPC contract to be tendered.',
    pack: {
      label: '10 MWp factory solar PV · NPV +$1.7M @ 8% · IRR 11.2%',
      text: 'Calculator output (after tax, nominal USD, end-of-year): capex $6.0M ($0.60/Wp, estimate); year-1 output 18 GWh; avoided tariff $0.0533/kWh escalating 1%/yr; O&M $120k/yr +2.5%/yr; inverter replacement $350k in year 12; 25-year life; 20% tax. NPV +$1.7M at 8% WACC; IRR 11.2%; simple payback 8.1 yrs; discounted payback ~14 yrs. Tornado: tariff and capex drive the largest NPV swings; NPV turns negative if capex exceeds ~$0.79/Wp; NPV at the 12% hurdle is about −$0.3M.',
    },
  },
  {
    id: 'hvac',
    title: 'Acquire a Dubai HVAC contractor',
    decision: 'Acquire Gulf Cooling Services, a Dubai HVAC maintenance contractor (AED 180M revenue, AED 21M EBITDA, 1,100 technicians, mostly expatriate), for AED 260M to launch a facilities-services arm.',
  },
  {
    id: 'whr',
    title: 'Waste-heat-to-power at Yanbu',
    decision: 'Install a 5 MWe waste-heat-to-power unit on kiln 2 at our Yanbu cement plant for $10M, with the tie-in done during the next 10-week turnaround.',
  },
  {
    id: 'ev',
    title: 'Riyadh EV fast-charging network',
    decision: 'Enter Riyadh public EV fast-charging with 60 × 150 kW chargers at malls and fuel stations, $9M over two years, before the state-backed EVIQ network scales.',
  },
  {
    id: 'rhq',
    title: 'Move regional HQ to Riyadh',
    decision: 'Move our regional headquarters from Dubai to Riyadh within 12 months so we qualify for Saudi government contracts under the RHQ rule; about 140 staff affected.',
  },
  {
    id: 'price',
    title: 'Cut clinker price 10% to fill kilns',
    decision: 'Cut our domestic clinker and cement price 10% to fill spare kiln capacity and take share from two regional rivals.',
  },
];

const v = (stance, confidence, headline, reasons, risk, conditions, metric, assumptions = [], red_line = false) =>
  ({ stance, confidence, headline, reasons, risk_flag: { title: risk[0], detail: risk[1], severity: risk[2] }, conditions, key_metric: { label: metric[0], value: metric[1] }, red_line, assumptions });

export const SAMPLE_RUNS = {
  solar: {
    verdicts: {
      finance: v('conditional', 62,
        'At 11.2% IRR this misses our 12% hurdle by 80 basis points; I support it only if capex or financing closes that gap.',
        ['NPV is +$1.7M at an 8% discount rate but slightly negative at the 12% hurdle. The case lives or dies on which rate we use.',
          'Simple payback of 8.1 years ties up $6M against a tariff that has barely moved since 2018. The savings are real but thin.',
          'The tornado puts tariff and capex on top: a 15% capex overrun erases most of the value at WACC.'],
        ['Capex overrun on an unbid estimate', '$0.60/Wp is a triangulated figure, not a tender result. At $0.70/Wp the IRR drops below 10%.', 'med'],
        ['EPC bids at or below $0.55/Wp before commitment', 'Term sheet for a sustainability-linked loan below 7%', 'Release capital in two tranches: rooftop first, ground-mount on performance'],
        ['IRR vs hurdle', '11.2% vs 12.0%'], ['Hurdle of 12% per company context', '20% tax on the foreign-owned share']),
      strategy: v('support', 74,
        'A cheap real option on the energy transition, and a credential we will need in Aramco-tier and giga-project supplier programmes.',
        ['Eastern Province customers are starting to ask suppliers for Scope 2 data; owning low-carbon power becomes a qualification, not a perk.',
          'It proves a capability we can repeat at our other three plants. A platform, not a one-off.',
          'Waiting buys little: module prices sit near the floor and tariff direction is up, not down.'],
        ['Tariff reform could cut the other way', 'If intensive-use industrial customers get a cheaper band, the avoided-cost savings shrink.', 'low'],
        [], ['Follow-on sites', '3 plants, ~25 MWp (est.)']),
      legal: v('conditional', 70,
        'Workable, subject to SERA’s self-consumption rules, a bankable EPC contract and a look at the roof leases.',
        ['Behind-the-meter generation of this size needs registration and an interconnection approval; allow three to six months.',
          'The EPC contract must carry yield performance guarantees and liquidated damages for delay, capped at a sensible level.',
          'Rooftop sections on leased buildings need a lease term covering the 25-year asset life, or removal rights.'],
        ['Lease shorter than asset life', 'Without an extension the rooftop array could be stranded mid-life and become a reinstatement liability.', 'med'],
        ['Regulatory registration as a condition precedent to notice to proceed', 'Performance guarantee; LD cap at 10% of contract value', 'Lease extension or removal-and-reinstatement clause'],
        ['Approvals required', '2 (registration, interconnection)'], ['Some rooftop area is on leased buildings']),
      operations: v('conditional', 66,
        'Buildable and technically low-risk, but $0.60/Wp is a Class 4 number and Jubail soiling will eat yield without a cleaning regime.',
        ['Estimate maturity is roughly AACE Class 4. We need a FEED-level design and firm bids before this becomes a budget.',
          'Coastal humidity plus dust means 4-7% soiling losses without robotic or weekly cleaning; the 1,800 kWh/kWp assumes we manage it.',
          'The tie-in to the plant switchboard needs a short shutdown; the next turnaround is the obvious window.'],
        ['Yield shortfall from soiling', 'Every 5% of lost yield takes roughly $0.4M off NPV at 8%.', 'med'],
        ['Fund FEED and a site yield study before FID', 'Dry robotic cleaning priced into O&M', 'Tie-in scheduled in the Q1 turnaround'],
        ['Estimate class', 'Class 4, need Class 3']),
      marketing: v('support', 71,
        'Two of our biggest customers now score suppliers on carbon. This gives us a real low-carbon story instead of a brochure.',
        ['Two key accounts added supplier Scope 2 questions to their 2026 pre-qualification. Today we answer “none”.',
          'Saudi-made, lower-carbon fabrication is a differentiator on giga-project packages that weight local content and sustainability.',
          'It is visible: an array at the plant gate is a site-visit asset for the sales team.'],
        ['Green claims running ahead of the data', 'Solar covers about a quarter of load. Marketing “solar-powered” output would invite greenwashing challenges.', 'low'],
        [], ['Accounts asking for Scope 2 data', '2 of top 5']),
      esg: v('support', 84,
        'Cuts roughly 11,700 tCO2e a year of Scope 2 and puts the 2060 pledge on a credible path at a positive NPV.',
        ['18 GWh a year displaces grid power at about 0.65 tCO2e/MWh: ~11,700 t of Scope 2 in year one.',
          'At a $50/t shadow carbon price that is ~$0.6M a year of avoided transition cost, which clears the hurdle comfortably.',
          'It qualifies for green or sustainability-linked financing, which Finance can use to close its IRR gap.'],
        ['Water use for module cleaning', 'Wet cleaning at Jubail would burn desalinated water. Specify dry robotic cleaning or treated effluent.', 'low'],
        [], ['Scope 2 avoided', '~11,700 tCO2e/yr (est.)'], ['Grid emission factor 0.65 tCO2e/MWh']),
      hr: v('support', 60,
        'Small people footprint, and the O&M roles are good openings for Saudi technicians.',
        ['About four permanent O&M roles plus a contracted cleaning crew. No change-management load on the plant.',
          'Solar technician roles fit HRDF-supported training and strengthen our Nitaqat position.',
          'We have no in-house PV expertise: one experienced asset manager must be hired or seconded from the EPC for year one.'],
        ['Key-person dependency', 'With a single PV specialist, performance monitoring stops when that person leaves.', 'low'],
        [], ['Critical hires', '1 PV asset manager + 3 technicians']),
    },
    brain: {
      decision: 'go_with_conditions', confidence: 72,
      headline: 'Approve in principle and fund FEED now; release the $6M only when bids and financing lift the IRR above our 12% hurdle.',
      rationale: 'Six of seven departments back the project in substance. The dispute is Finance’s 80-basis-point hurdle gap, which the other departments’ own conditions (firm bids, green financing) can close. It is a two-way door at FEED and a one-way door at FID, so the Brain gates the commitment instead of deciding it today.',
      reversibility: 'mixed',
      consensus: ['The project is technically simple and NPV-positive at the corporate WACC.', 'Carbon and customer value are real and growing.', 'The $0.60/Wp estimate is not yet a budget.'],
      disagreements: [
        { between: ['Finance', 'Sustainability & ESG'], issue: 'Whether a sub-hurdle IRR is acceptable for ~11,700 t/yr of Scope 2 reduction.', resolution: 'Neither wins outright. The carbon value is used to access cheaper green money, not to waive the hurdle.' },
        { between: ['Operations & Engineering', 'Strategy & Corp Dev'], issue: 'Strategy sees no gain in waiting; Operations wants a Class 3 estimate first.', resolution: 'FEED and EPC bidding run in parallel for about four months, so the delay is short and buys a real number.' },
      ],
      hinge_tradeoff: {
        title: 'Return discipline vs. decarbonisation timing',
        side_a: 'Finance: hold the 12% hurdle. An 11.2% IRR on a Class 4 estimate is not good enough.',
        side_b: 'ESG and Strategy: the carbon and customer value are real and the NPV is already positive at WACC.',
        what_would_have_to_be_true: 'EPC bids at or below $0.55/Wp, or financing under 7%, lifts the IRR above 12% and dissolves the conflict.',
        why_it_decides: 'Every other concern (leases, registration, soiling) is a condition, not a reason to stop.',
      },
      vetoes: [],
      conditions: [
        { condition: 'Firm EPC bids at or below $0.55/Wp', owner: 'Operations & Engineering', gate: 'Before FID, about four months' },
        { condition: 'Term sheet for a sustainability-linked or green loan', owner: 'Finance', gate: 'Before FID' },
        { condition: 'Registration and interconnection approval', owner: 'Legal & Risk', gate: 'Condition precedent to notice to proceed' },
        { condition: 'Lease cover for 25 years on rooftop areas', owner: 'Legal & Risk', gate: 'Before FID' },
        { condition: 'Dry cleaning regime priced into O&M', owner: 'Operations & Engineering', gate: 'In EPC scope' },
      ],
      kill_criteria: ['Best EPC bid above $0.65/Wp', 'No financing below 8% within six months', 'Registration refused or delayed beyond nine months'],
      premortem_top_failure: 'Soiling and a slipped tie-in cut first-year yield by 10%; the project reported an IRR near 9% and the second site was cancelled.',
      dissent_recorded: [{ department: 'Finance', view: 'Would not approve at 11.2% on today’s estimate.', what_would_change_their_mind: 'Firm bids or financing that clear 12% after tax.' }],
      next_steps: ['Issue FEED and EPC requests for quotation this month', 'Treasury to approach two banks for sustainability-linked terms', 'Legal to open the registration file', 'Return to committee with a Class 3 estimate in about four months'],
      your_call: {
        needed: true,
        question: 'If bids land at $0.58/Wp and the IRR ends at 11.6%, do we build anyway for the carbon and customer value?',
        side_a: 'Hold the line: the hurdle is the hurdle. Wait for better terms or drop it.',
        side_b: 'Build: accept a slightly sub-hurdle return for ~11,700 t/yr of Scope 2 cuts and supplier credentials.',
        brain_lean: 'Build if the gap is under 50 basis points and the financing is green; otherwise hold.',
      },
    },
  },

  hvac: {
    verdicts: {
      finance: v('conditional', 58,
        '12.4× EBITDA for a labour-heavy contractor with thin margins leaves no room for integration slippage.',
        ['AED 260M is 12.4× EBITDA. Listed GCC facilities-management peers trade nearer 8-10×.',
          'An 11.7% EBITDA margin on labour-intensive contracts: a one-point wage rise removes about a sixth of profit.',
          'Cross-sell synergies into our client base are unproven, so I put no value on them in the price.'],
        ['Working-capital trap', 'Contractors collect slowly from developers. DSO above 120 days would absorb about AED 60M of cash.', 'med'],
        ['Price at or below AED 210M (10×)', 'Earn-out on 2027 EBITDA for any balance', 'Quality-of-earnings review including receivables ageing'],
        ['EV/EBITDA', '12.4× vs 8-10× peers (est.)'], ['Peer multiples from recent regional FM deals']),
      strategy: v('support', 76,
        'Facilities services is the recurring-revenue adjacency we keep talking about; buying a platform beats building one.',
        ['Maintenance contracts renew annually and run counter-cyclical to our project business.',
          'A Dubai base with 1,100 technicians is a platform for Riyadh giga-project FM tenders.',
          'Building this organically means four to five years of hiring against much larger incumbents.'],
        ['Founder-led culture walks out', 'Founder-owned contractors often lose key supervisors in the first year after sale.', 'med'],
        [], ['Recurring revenue share', '0% → ~15% of group (est.)']),
      legal: v('conditional', 64,
        'Acceptable subject to labour and contract diligence. In this sector the liabilities sit in accommodation, wages and change-of-control clauses.',
        ['Maintenance contracts often carry change-of-control termination rights; we need consent from the top clients before signing.',
          'End-of-service gratuity for 1,100 workers must be quantified and reserved in the price.',
          'Wage Protection System compliance history and accommodation standards are sanctionable exposures that transfer in a share deal.'],
        ['Uncapped historic labour liabilities', 'Pre-closing wage or accommodation breaches travel with the company in a share purchase.', 'high'],
        ['Specific indemnity for pre-closing labour claims backed by 15% escrow', 'Consent from the top 10 clients as a condition precedent', 'W&I insurance'],
        ['Gratuity liability (est.)', 'AED 25-30M']),
      operations: v('conditional', 60,
        'Their incident log and maintenance-system data will tell us more than the deck. Heat-stress on 48°C rooftops is the exposure.',
        ['HVAC maintenance is safe only with disciplined permit-to-work and heat-stress control. We have seen none of their incident data.',
          'Their scheduling runs on spreadsheets; integrating into our CMMS is a 12-month job.',
          'Refrigerant handling (legacy R-22, R-410A) needs certified technicians and recovery equipment.'],
        ['Heat-stress safety exposure', 'Midday work-ban compliance and site supervision quality are unknown.', 'high'],
        ['Three-year incident log and an independent site audit', 'CMMS integration plan and budget'],
        ['Safety data seen', 'None yet']),
      marketing: v('support', 80,
        'Three of our industrial clients already ask us who maintains their HVAC. This lets us say “we do”.',
        ['Cross-sell FM into our 40 industrial accounts: ten contracts at AED 1.5M is AED 15M of revenue.',
          'Bundled build-and-maintain offers win on lifecycle cost in giga-project tenders.',
          'Keep their brand for two years to protect client relationships.'],
        ['Client churn at change of ownership', 'Owner-managed accounts may follow the founder.', 'med'],
        [], ['Cross-sell revenue, year 2', 'AED 15M (est.)']),
      esg: v('conditional', 55,
        'Worker welfare is the material issue here, not carbon: 1,100 migrant technicians means housing and wage standards we must be able to defend.',
        ['Accommodation conditions and recruitment-fee practices are the most likely ESG controversy for a GCC contractor.',
          'Refrigerant leakage is a real Scope 1 source; high-GWP gases need a phase-down plan.',
          'Efficiency retrofits for clients could become a green revenue line.'],
        ['Worker-welfare controversy', 'Recruitment fees paid by workers or substandard housing would breach our supplier code.', 'high'],
        ['Third-party worker-welfare audit before signing', 'Refrigerant management and phase-down plan'],
        ['Refrigerant Scope 1 (est.)', '~3,000 tCO2e/yr']),
      hr: v('oppose', 62,
        '1,100 technicians, few Emiratis, and a founder whose supervisors will walk: we are buying a people business we don’t know how to run.',
        ['Emiratisation adds 2% of skilled roles a year: roughly 20 Emirati hires a year in a trade Emiratis rarely enter.',
          'Supervisors hold the client relationships. Without retention packages we lose the value we are paying for.',
          'Our HR function has no UAE labour-law bench; we would be integrating from Dammam.'],
        ['Emiratisation shortfall fines', 'Monthly fines per unfilled role; a two-year shortfall could exceed AED 4M (est.).', 'med'],
        [], ['Emirati hires needed per year', '~20 (est.)']),
    },
    brain: {
      decision: 'go_with_conditions', confidence: 61,
      headline: 'Proceed to a non-binding offer at AED 210M with an earn-out; sign only after labour, safety and welfare diligence comes back clean.',
      rationale: 'Strategy and Marketing make a real case for a recurring-revenue platform we cannot build quickly, and Finance’s objection is about price, which is negotiable. But three departments independently point at the same unknown: the 1,100-person workforce. Operations holds a safety veto that only diligence can clear, and this is a one-way door, so the Brain buys information before commitment.',
      reversibility: 'one_way',
      consensus: ['The strategic logic of recurring FM revenue is sound.', 'The asking price is above peer multiples.', 'The biggest unknowns sit in the workforce, not the market.'],
      disagreements: [
        { between: ['Strategy & Corp Dev', 'HR & Talent'], issue: 'Whether we can run a 1,100-person field-services business from Dammam.', resolution: 'Retention agreements with named supervisors and a UAE HR lead are conditions of signing, not integration tasks.' },
        { between: ['Marketing & Sales', 'Finance'], issue: 'Whether cross-sell revenue belongs in the price.', resolution: 'Finance wins on price (no synergy value paid upfront); Marketing’s upside is captured through the earn-out structure.' },
      ],
      hinge_tradeoff: {
        title: 'Paying for a platform vs. inheriting a people liability',
        side_a: 'Strategy and Marketing: a recurring-revenue platform we cannot build in five years.',
        side_b: 'HR, ESG and Legal: the value and the liabilities both sit in a workforce we don’t yet know how to manage.',
        what_would_have_to_be_true: 'Diligence finds clean wage, housing and safety records, and at least 70% of named supervisors sign retention.',
        why_it_decides: 'Price can be negotiated; people liabilities can only be discovered.',
      },
      vetoes: [{ department: 'Operations & Engineering', issue: 'Heat-stress safety exposure', cleared_by: 'Three-year incident log and site audit with no systemic findings' }],
      conditions: [
        { condition: 'Offer at AED 210M plus earn-out on 2027 EBITDA', owner: 'Finance', gate: 'Non-binding offer' },
        { condition: 'Labour, WPS and accommodation diligence with specific indemnity and 15% escrow', owner: 'Legal & Risk', gate: 'Before signing' },
        { condition: 'Independent safety audit and incident-log review', owner: 'Operations & Engineering', gate: 'Before signing' },
        { condition: 'Retention agreements with named supervisors', owner: 'HR & Talent', gate: 'Signing' },
        { condition: 'Third-party worker-welfare audit', owner: 'Sustainability & ESG', gate: 'Before signing' },
      ],
      kill_criteria: ['Seller refuses anything below AED 230M without an earn-out', 'Diligence finds wage-protection or accommodation breaches', 'Fewer than 70% of named supervisors sign retention'],
      premortem_top_failure: 'Key supervisors left within a year, taking three anchor contracts with them, while a housing audit forced an unbudgeted AED 20M upgrade.',
      dissent_recorded: [{ department: 'HR & Talent', view: 'Opposes owning a large expatriate field workforce without UAE HR capability.', what_would_change_their_mind: 'A UAE HR lead hired before close and supervisor retention above 70%.' }],
      next_steps: ['Submit a non-binding offer at AED 210M with earn-out', 'Appoint labour, safety and welfare diligence advisers', 'Open retention talks with the founder on named supervisors', 'Recruit a UAE HR lead in parallel'],
      your_call: { needed: false, question: '', side_a: '', side_b: '', brain_lean: '' },
    },
  },
};
