// Builds js/cases.data.js from docs/research/cases.md so the case bank stays
// editable as prose. Run: npm run build:cases
import { readFileSync, writeFileSync } from 'node:fs';

const md = readFileSync(new URL('../docs/research/cases.md', import.meta.url), 'utf8').replace(/\r\n/g, '\n');

// Interview format each case mirrors, and what makes it hard (Darden-style drivers).
const FORMAT = {
  S1: 'interviewer-led', S2: 'candidate-led', S3: 'candidate-led', S4: 'interviewer-led',
  S5: 'candidate-led', S6: 'interviewer-led', S7: 'candidate-led', S8: 'interviewer-led',
  T1: 'engineering', T2: 'engineering', T3: 'engineering', T4: 'engineering',
  T5: 'engineering', T6: 'engineering', T7: 'engineering', T8: 'engineering',
};
const DRIVERS = {
  S5: ['multi-stage', 'messy-data', 'second-order'], S6: ['multi-stage', 'trap'],
  S7: ['multi-stage', 'second-order', 'messy-data'], S8: ['second-order', 'trap'],
  T1: ['discounting'], T2: ['unit-conversion'], T4: ['discounting'],
  T5: ['what-must-be-true', 'discounting'], T6: ['trap', 'second-order'],
  T7: ['multi-stage', 'discounting', 'trap'], T8: ['multi-stage', 'discounting'],
};
const MINUTES = { entry: 20, advanced: 35 };

const FIELD = /^\*\*(Prompt|Data exhibits|Hint|Model structure|Model reasoning walkthrough|Answer|Synthesis|Frameworks used)\b[^\n]*?:\*{0,2}\s*(.*)$/;
const KEYS = { 'Prompt': 'prompt', 'Data exhibits': 'exhibits', 'Hint': 'hint', 'Model structure': 'structure',
  'Model reasoning walkthrough': 'walkthrough', 'Answer': 'answer', 'Synthesis': 'synthesis', 'Frameworks used': 'frameworks' };

function parseCase(block) {
  const lines = block.split('\n');
  const c = {};
  let cur = null;
  const buf = {};
  for (const line of lines.slice(1)) {
    const meta = line.match(/^- \*\*(id|title|type|track|difficulty|setting):\*\*\s*(.+)$/);
    if (meta && !cur) { c[meta[1]] = meta[2].trim(); continue; }
    const f = line.match(FIELD);
    if (f) {
      cur = KEYS[f[1]];
      buf[cur] = [];
      const note = line.match(/^\*\*Data exhibits\*\*\s*\(([^)]*)\)/);
      if (note) c.exhibitsNote = note[1];
      if (f[2] && !line.startsWith('**Data exhibits')) buf[cur].push(f[2]);
      continue;
    }
    if (line.trim() === '---') break;
    if (cur) buf[cur].push(line);
  }
  for (const k in buf) buf[k] = buf[k].join('\n').trim();
  c.prompt = buf.prompt;
  c.hint = buf.hint;
  c.structure = buf.structure;
  c.walkthrough = buf.walkthrough;
  c.answer = buf.answer;
  c.synthesis = buf.synthesis.replace(/^"|"$/g, '');
  c.frameworks = [...buf.frameworks.matchAll(/`([^`]+)`/g)].map(m => m[1]);
  c.exhibits = splitExhibits(buf.exhibits);
  c.format = FORMAT[c.id];
  c.drivers = DRIVERS[c.id] || [];
  c.minutes = MINUTES[c.difficulty];
  return c;
}

// Each top-level bullet (with its children) or each table is one requestable exhibit.
function splitExhibits(text) {
  const items = [];
  let cur = [];
  const flush = () => { if (cur.length) items.push(cur.join('\n').trim()); cur = []; };
  for (const line of text.split('\n')) {
    if (!line.trim()) { continue; }
    const isTable = line.trim().startsWith('|');
    const prevTable = cur.length && cur[cur.length - 1].trim().startsWith('|');
    if (isTable) { if (!prevTable) flush(); cur.push(line); continue; }
    if (/^- /.test(line)) { flush(); cur.push(line); continue; }
    if (prevTable) flush();
    cur.push(line);
  }
  flush();
  return items;
}

function section(title) {
  const start = md.indexOf(title);
  const next = md.indexOf('\n## ', start + 5);
  return md.slice(start, next === -1 ? undefined : next);
}

const bank = section('## 3. Case Bank');
const cases = bank.split(/\n(?=### [ST]\d: )/).filter(b => /^### [ST]\d: /.test(b)).map(parseCase);

const frameworkSection = section('## 1. Framework Reference');
const frameworks = frameworkSection.split(/\n(?=### 1\.\d )/).filter(b => /^### 1\.\d /.test(b)).map(b => {
  const [head, ...rest] = b.split('\n');
  return { title: head.replace(/^### 1\.\d\s+/, ''), md: rest.join('\n').trim() };
});
const calibration = section('## 2. Difficulty Calibration').split('\n').slice(1).join('\n').trim();

for (const c of cases) {
  for (const k of ['id', 'title', 'track', 'difficulty', 'prompt', 'hint', 'structure', 'walkthrough', 'answer', 'synthesis']) {
    if (!c[k]) throw new Error(`Case ${c.id || '?'} is missing ${k}`);
  }
  if (!c.exhibits.length) throw new Error(`Case ${c.id} has no exhibits`);
}

const out = `// Generated by scripts/build-cases.mjs from docs/research/cases.md. Do not edit by hand.
export const CASES = ${JSON.stringify(cases, null, 1)};

export const FRAMEWORKS = ${JSON.stringify(frameworks, null, 1)};

export const CALIBRATION = ${JSON.stringify(calibration)};
`;
writeFileSync(new URL('../js/cases.data.js', import.meta.url), out);
console.log(`Wrote ${cases.length} cases and ${frameworks.length} framework notes.`);
